name: CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
      - run: npx prettier --check "src/**/*.{js,jsx}"
      - run: npx eslint src/**/*.{js,jsx}"
      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: test-results.xml
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact
          path: build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: build-artifact
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
