name: CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
      - run: npm run prettier-check
      - run: npm run lint-check
      - name: Upload test results
        uses: actions/upload-artifact@v1
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
